//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace TesteWebService.WebServiceTeste {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WebServiceTesteSoap", Namespace="http://apps.cm-gaia.pt/")]
    public partial class WebServiceTeste : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ObterInteiroOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObterStringOperationCompleted;
        
        private System.Threading.SendOrPostCallback QuemDizOlaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObterObjectoComplexoOperationCompleted;
        
        private System.Threading.SendOrPostCallback AtualizarUtilizadorTestesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GuardarUtilizadorTestesOperationCompleted;
        
        private System.Threading.SendOrPostCallback ApagarUtilizadorTestesOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObterUtilizadorTestesOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObterListaUtilizadoresTestesOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WebServiceTeste() {
            this.Url = global::TesteWebService.Properties.Settings.Default.TesteWebService_WebServiceTeste_WebServiceTeste;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ObterInteiroCompletedEventHandler ObterInteiroCompleted;
        
        /// <remarks/>
        public event ObterStringCompletedEventHandler ObterStringCompleted;
        
        /// <remarks/>
        public event QuemDizOlaCompletedEventHandler QuemDizOlaCompleted;
        
        /// <remarks/>
        public event ObterObjectoComplexoCompletedEventHandler ObterObjectoComplexoCompleted;
        
        /// <remarks/>
        public event AtualizarUtilizadorTestesCompletedEventHandler AtualizarUtilizadorTestesCompleted;
        
        /// <remarks/>
        public event GuardarUtilizadorTestesCompletedEventHandler GuardarUtilizadorTestesCompleted;
        
        /// <remarks/>
        public event ApagarUtilizadorTestesCompletedEventHandler ApagarUtilizadorTestesCompleted;
        
        /// <remarks/>
        public event ObterUtilizadorTestesCompletedEventHandler ObterUtilizadorTestesCompleted;
        
        /// <remarks/>
        public event ObterListaUtilizadoresTestesCompletedEventHandler ObterListaUtilizadoresTestesCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://apps.cm-gaia.pt/ObterInteiro", RequestNamespace="http://apps.cm-gaia.pt/", ResponseNamespace="http://apps.cm-gaia.pt/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int ObterInteiro() {
            object[] results = this.Invoke("ObterInteiro", new object[0]);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void ObterInteiroAsync() {
            this.ObterInteiroAsync(null);
        }
        
        /// <remarks/>
        public void ObterInteiroAsync(object userState) {
            if ((this.ObterInteiroOperationCompleted == null)) {
                this.ObterInteiroOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObterInteiroOperationCompleted);
            }
            this.InvokeAsync("ObterInteiro", new object[0], this.ObterInteiroOperationCompleted, userState);
        }
        
        private void OnObterInteiroOperationCompleted(object arg) {
            if ((this.ObterInteiroCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObterInteiroCompleted(this, new ObterInteiroCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://apps.cm-gaia.pt/ObterString", RequestNamespace="http://apps.cm-gaia.pt/", ResponseNamespace="http://apps.cm-gaia.pt/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ObterString() {
            object[] results = this.Invoke("ObterString", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ObterStringAsync() {
            this.ObterStringAsync(null);
        }
        
        /// <remarks/>
        public void ObterStringAsync(object userState) {
            if ((this.ObterStringOperationCompleted == null)) {
                this.ObterStringOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObterStringOperationCompleted);
            }
            this.InvokeAsync("ObterString", new object[0], this.ObterStringOperationCompleted, userState);
        }
        
        private void OnObterStringOperationCompleted(object arg) {
            if ((this.ObterStringCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObterStringCompleted(this, new ObterStringCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://apps.cm-gaia.pt/QuemDizOla", RequestNamespace="http://apps.cm-gaia.pt/", ResponseNamespace="http://apps.cm-gaia.pt/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string QuemDizOla(string nome) {
            object[] results = this.Invoke("QuemDizOla", new object[] {
                        nome});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void QuemDizOlaAsync(string nome) {
            this.QuemDizOlaAsync(nome, null);
        }
        
        /// <remarks/>
        public void QuemDizOlaAsync(string nome, object userState) {
            if ((this.QuemDizOlaOperationCompleted == null)) {
                this.QuemDizOlaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQuemDizOlaOperationCompleted);
            }
            this.InvokeAsync("QuemDizOla", new object[] {
                        nome}, this.QuemDizOlaOperationCompleted, userState);
        }
        
        private void OnQuemDizOlaOperationCompleted(object arg) {
            if ((this.QuemDizOlaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QuemDizOlaCompleted(this, new QuemDizOlaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://apps.cm-gaia.pt/ObterObjectoComplexo", RequestNamespace="http://apps.cm-gaia.pt/", ResponseNamespace="http://apps.cm-gaia.pt/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ComplexObject ObterObjectoComplexo() {
            object[] results = this.Invoke("ObterObjectoComplexo", new object[0]);
            return ((ComplexObject)(results[0]));
        }
        
        /// <remarks/>
        public void ObterObjectoComplexoAsync() {
            this.ObterObjectoComplexoAsync(null);
        }
        
        /// <remarks/>
        public void ObterObjectoComplexoAsync(object userState) {
            if ((this.ObterObjectoComplexoOperationCompleted == null)) {
                this.ObterObjectoComplexoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObterObjectoComplexoOperationCompleted);
            }
            this.InvokeAsync("ObterObjectoComplexo", new object[0], this.ObterObjectoComplexoOperationCompleted, userState);
        }
        
        private void OnObterObjectoComplexoOperationCompleted(object arg) {
            if ((this.ObterObjectoComplexoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObterObjectoComplexoCompleted(this, new ObterObjectoComplexoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://apps.cm-gaia.pt/AtualizarUtilizadorTestes", RequestNamespace="http://apps.cm-gaia.pt/", ResponseNamespace="http://apps.cm-gaia.pt/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool AtualizarUtilizadorTestes(UtilizadorTestes ut) {
            object[] results = this.Invoke("AtualizarUtilizadorTestes", new object[] {
                        ut});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void AtualizarUtilizadorTestesAsync(UtilizadorTestes ut) {
            this.AtualizarUtilizadorTestesAsync(ut, null);
        }
        
        /// <remarks/>
        public void AtualizarUtilizadorTestesAsync(UtilizadorTestes ut, object userState) {
            if ((this.AtualizarUtilizadorTestesOperationCompleted == null)) {
                this.AtualizarUtilizadorTestesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAtualizarUtilizadorTestesOperationCompleted);
            }
            this.InvokeAsync("AtualizarUtilizadorTestes", new object[] {
                        ut}, this.AtualizarUtilizadorTestesOperationCompleted, userState);
        }
        
        private void OnAtualizarUtilizadorTestesOperationCompleted(object arg) {
            if ((this.AtualizarUtilizadorTestesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AtualizarUtilizadorTestesCompleted(this, new AtualizarUtilizadorTestesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://apps.cm-gaia.pt/GuardarUtilizadorTestes", RequestNamespace="http://apps.cm-gaia.pt/", ResponseNamespace="http://apps.cm-gaia.pt/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int GuardarUtilizadorTestes(UtilizadorTestes ut) {
            object[] results = this.Invoke("GuardarUtilizadorTestes", new object[] {
                        ut});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void GuardarUtilizadorTestesAsync(UtilizadorTestes ut) {
            this.GuardarUtilizadorTestesAsync(ut, null);
        }
        
        /// <remarks/>
        public void GuardarUtilizadorTestesAsync(UtilizadorTestes ut, object userState) {
            if ((this.GuardarUtilizadorTestesOperationCompleted == null)) {
                this.GuardarUtilizadorTestesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGuardarUtilizadorTestesOperationCompleted);
            }
            this.InvokeAsync("GuardarUtilizadorTestes", new object[] {
                        ut}, this.GuardarUtilizadorTestesOperationCompleted, userState);
        }
        
        private void OnGuardarUtilizadorTestesOperationCompleted(object arg) {
            if ((this.GuardarUtilizadorTestesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GuardarUtilizadorTestesCompleted(this, new GuardarUtilizadorTestesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://apps.cm-gaia.pt/ApagarUtilizadorTestes", RequestNamespace="http://apps.cm-gaia.pt/", ResponseNamespace="http://apps.cm-gaia.pt/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool ApagarUtilizadorTestes(int id) {
            object[] results = this.Invoke("ApagarUtilizadorTestes", new object[] {
                        id});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ApagarUtilizadorTestesAsync(int id) {
            this.ApagarUtilizadorTestesAsync(id, null);
        }
        
        /// <remarks/>
        public void ApagarUtilizadorTestesAsync(int id, object userState) {
            if ((this.ApagarUtilizadorTestesOperationCompleted == null)) {
                this.ApagarUtilizadorTestesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnApagarUtilizadorTestesOperationCompleted);
            }
            this.InvokeAsync("ApagarUtilizadorTestes", new object[] {
                        id}, this.ApagarUtilizadorTestesOperationCompleted, userState);
        }
        
        private void OnApagarUtilizadorTestesOperationCompleted(object arg) {
            if ((this.ApagarUtilizadorTestesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ApagarUtilizadorTestesCompleted(this, new ApagarUtilizadorTestesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://apps.cm-gaia.pt/ObterUtilizadorTestes", RequestNamespace="http://apps.cm-gaia.pt/", ResponseNamespace="http://apps.cm-gaia.pt/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public UtilizadorTestes ObterUtilizadorTestes(int id) {
            object[] results = this.Invoke("ObterUtilizadorTestes", new object[] {
                        id});
            return ((UtilizadorTestes)(results[0]));
        }
        
        /// <remarks/>
        public void ObterUtilizadorTestesAsync(int id) {
            this.ObterUtilizadorTestesAsync(id, null);
        }
        
        /// <remarks/>
        public void ObterUtilizadorTestesAsync(int id, object userState) {
            if ((this.ObterUtilizadorTestesOperationCompleted == null)) {
                this.ObterUtilizadorTestesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObterUtilizadorTestesOperationCompleted);
            }
            this.InvokeAsync("ObterUtilizadorTestes", new object[] {
                        id}, this.ObterUtilizadorTestesOperationCompleted, userState);
        }
        
        private void OnObterUtilizadorTestesOperationCompleted(object arg) {
            if ((this.ObterUtilizadorTestesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObterUtilizadorTestesCompleted(this, new ObterUtilizadorTestesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://apps.cm-gaia.pt/ObterListaUtilizadoresTestes", RequestNamespace="http://apps.cm-gaia.pt/", ResponseNamespace="http://apps.cm-gaia.pt/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public UtilizadorTestes[] ObterListaUtilizadoresTestes() {
            object[] results = this.Invoke("ObterListaUtilizadoresTestes", new object[0]);
            return ((UtilizadorTestes[])(results[0]));
        }
        
        /// <remarks/>
        public void ObterListaUtilizadoresTestesAsync() {
            this.ObterListaUtilizadoresTestesAsync(null);
        }
        
        /// <remarks/>
        public void ObterListaUtilizadoresTestesAsync(object userState) {
            if ((this.ObterListaUtilizadoresTestesOperationCompleted == null)) {
                this.ObterListaUtilizadoresTestesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObterListaUtilizadoresTestesOperationCompleted);
            }
            this.InvokeAsync("ObterListaUtilizadoresTestes", new object[0], this.ObterListaUtilizadoresTestesOperationCompleted, userState);
        }
        
        private void OnObterListaUtilizadoresTestesOperationCompleted(object arg) {
            if ((this.ObterListaUtilizadoresTestesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObterListaUtilizadoresTestesCompleted(this, new ObterListaUtilizadoresTestesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://apps.cm-gaia.pt/")]
    public partial class ComplexObject {
        
        private int idField;
        
        private string prim_nomeField;
        
        private string ult_nomeField;
        
        /// <remarks/>
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Prim_nome {
            get {
                return this.prim_nomeField;
            }
            set {
                this.prim_nomeField = value;
            }
        }
        
        /// <remarks/>
        public string Ult_nome {
            get {
                return this.ult_nomeField;
            }
            set {
                this.ult_nomeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://apps.cm-gaia.pt/")]
    public partial class UtilizadorTestes {
        
        private int idField;
        
        private string nameField;
        
        private string emailField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void ObterInteiroCompletedEventHandler(object sender, ObterInteiroCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObterInteiroCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObterInteiroCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void ObterStringCompletedEventHandler(object sender, ObterStringCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObterStringCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObterStringCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void QuemDizOlaCompletedEventHandler(object sender, QuemDizOlaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QuemDizOlaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal QuemDizOlaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void ObterObjectoComplexoCompletedEventHandler(object sender, ObterObjectoComplexoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObterObjectoComplexoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObterObjectoComplexoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ComplexObject Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ComplexObject)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void AtualizarUtilizadorTestesCompletedEventHandler(object sender, AtualizarUtilizadorTestesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AtualizarUtilizadorTestesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AtualizarUtilizadorTestesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void GuardarUtilizadorTestesCompletedEventHandler(object sender, GuardarUtilizadorTestesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GuardarUtilizadorTestesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GuardarUtilizadorTestesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void ApagarUtilizadorTestesCompletedEventHandler(object sender, ApagarUtilizadorTestesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ApagarUtilizadorTestesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ApagarUtilizadorTestesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void ObterUtilizadorTestesCompletedEventHandler(object sender, ObterUtilizadorTestesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObterUtilizadorTestesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObterUtilizadorTestesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UtilizadorTestes Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UtilizadorTestes)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void ObterListaUtilizadoresTestesCompletedEventHandler(object sender, ObterListaUtilizadoresTestesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObterListaUtilizadoresTestesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObterListaUtilizadoresTestesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UtilizadorTestes[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UtilizadorTestes[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591